services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
     - "8000:8000"
    depends_on:
     - catalogdb
    environment:
     - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017?readPreference=primary&ssl=false"
     - "DatabaseSettings__DatabaseName=catalogdb"
     - "DatabaseSettings__ProductsCollectionName=Products"
     - "DatabaseSettings__BrandsCollectionName=Brands"
     - "DatabaseSettings__TypesCollectionName=Types"

  catalogdb:
    image: mongo
    container_name: catalogdb
    ports:
     - "27017:27017"
    volumes:
     - catalogdata:/data/db
  basketdb:
    image: redis:alpine
    container_name: basketdb
    restart: always
    ports:
     - "6379:6379"
    volumes:
     - basketdata:/data/db
  discountdb:
    image: postgres:13-alpine
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password@123
      - POSTGRES_DB=discountdb
    ports:
      - "5432:5432"
    volumes:
      - discountdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d discountdb"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
       - PGADMIN_DEFAULT_EMAIL=admin@ecommerce.com
       - PGADMIN_DEFAULT_PASSWORD=admin@123
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
      
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - basketdb
    environment:
      - "ASPNETCORE_ENVIRONMENT=http://+:8000"
      - "CacheSettings__connectionString=basketdb:6379"
      - "GrpcSettings__DiscountUrl=http://discount.api:8002"

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    # command: -H unix:///var/run/docker.sock
    ports:
      - 8005:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
    container_name: discount.api
    ports:
      - "8002:8000"
    depends_on:
       discountdb:
           condition: service_healthy
    environment:
      - "DatabaseSettings__ConnectionString=Host=discountdb;Port=5432;Database=discountdb;Username=admin;Password=password@123"
volumes:
  catalogdata:
  basketdata:
  portainer_data:
  discountdata:
  pgadmin_data: